dist: trusty
sudo: false
language: generic

env:
  global:
      - GIT_URL: https://github.com/clash-lang/clash-lang.github.io.git
      - HUGO_CHECKSUM: 39d3119cdb9ba5d6f1f1b43693e707937ce851791a2ea8d28003f49927c428f4
      - HUGO_URL: https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz

addons:
    apt:
        packages:
            - python-pygments

install:
    # Install hugo:
    - wget ${HUGO_URL} -O hugo.tar.gz
    - echo ${HUGO_CHECKSUM} hugo.tar.gz > checksums.txt
    - sha256sum -c checksums.txt --status
    - tar xzf hugo.tar.gz

script:
    - ./hugo

deploy:
  local-dir: public
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: false
  target-branch: gh-pages
  on:
    branch: src
